#!/usr/bin/env bash
# -*- mode: ruby -*-
# vi: set ft=ruby :

VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  # Use the same key for each machine
  config.ssh.insert_key = false

  config.vm.define "vagrant1" do |vagrant1|
    vagrant1.vm.box = "ubuntu"
    vagrant1.vm.network "forwarded_port", guest: 80, host: 8900
    vagrant1.vm.network "forwarded_port", guest: 443, host: 8443
  end
  config.vm.define "vagrant2" do |vagrant2|
    vagrant2.vm.box = "ubuntu"
    vagrant2.vm.network "forwarded_port", guest: 80, host: 8901
    vagrant2.vm.network "forwarded_port", guest: 443, host: 8444
  end
  config.vm.define "vagrant3" do |vagrant3|
    vagrant3.vm.box = "ubuntu"
    vagrant3.vm.network "forwarded_port", guest: 80, host: 8902
    vagrant3.vm.network "forwarded_port", guest: 443, host: 8445
  end
end
